# Node.js

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16'
  displayName: 'Install Node.js'
- task: BrowserStackConfig@0
  inputs:
    BrowserStackServiceEndPoint: 'BrowserStack'
- script: |
    npm install
    npm install cypress --save-dev
    npm install -g browserstack-cypress-cli
    browserstack-cypress run --build-name "azure-adarshTS.browserstack-cypress-example"
  displayName: 'npm install and build'
- task: BrowserStackResults@1
  inputs:
    browserstackProduct: 'automate'
