# Node.js
- task: BrowserStackResults@1
  inputs:
    browserstackProduct: 'automate'

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm install cypress --save-dev
    browserstack-cypress run
  displayName: 'npm install and build'
